name: "Hello World"
description: "Greet someone"
inputs:
  docker_actions_path:
    description: 'paths'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Run hello world
      run: ./say-hello.sh
      shell: bash
