name: "Hello World"
description: "Greet someone"
inputs:
  docker_actions_path:
    description: 'paths'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Run hello world
      run: |
        ${{ inputs.docker_actions_path }}/say-hello.sh
        echo "action path env variable: $GITHUB_ACTION_PATH"
      shell: bash
