name: "Hello World"
description: "Greet someone"
runs:
  using: "composite"
  steps:
    - name: Run hello world
      run: |
        $GITHUB_ACTION_PATH/say-hello.sh
        echo "action path env variable GITHUB_ACTION_PATH is: $GITHUB_ACTION_PATH"
        sleep 5m
      shell: bash
    - name: call local actions
      uses: ./.github/actions/hello-world
    - name: print everything
      run: |
        echo "github.action_path: ${{github.action_path}}"
        echo "github.event_path: ${{github.event_path}}"
        echo "github.workspace: ${{github.workspace}}"
      shell: bash
