name: "Hello World"
description: "Greet someone"
runs:
  using: "composite"
  steps:
    - name: Run hello world
      run: |
        echo "in composit action ${{ github.action_path }}"
        echo "in composit action ${{ github.workspace }}"
        ${{ github.action_path }}/say-hello.sh
      shell: bash
