name: "Hello World"
description: "Greet someone"
inputs:
  test_actions_path:
    description: 'paths'
    required: true
    default: 'World'
  test_actions_name:
    description: 'name'
    required: true
    default: 'world action'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  action-name:
    description: "action number"
    value: ${{ steps.random-number-generator.outputs.action-name }}
runs:
  using: "composite"
  steps:
    - name: Run hello world
      run: |
        $GITHUB_ACTION_PATH/say-hello.sh
        echo "action path env variable GITHUB_ACTION_PATH is: $GITHUB_ACTION_PATH"
      shell: bash
    - name: call local actions
      uses: ./.github/actions/hello-world
    - name: print everything
      run: |
        echo "github.action_path: ${{github.action_path}}"
        echo "github.event_path: ${{github.event_path}}"
        echo "github.workspace: ${{github.workspace}}"
      shell: bash
    - name: Random Number Generator
      id: random-number-generator
      run: |
        echo ${{ inputs.test_actions_path }}
        echo "random-number=${{ inputs.test_actions_path }}" >> $GITHUB_OUTPUT
        echo ${{ inputs.test_actions_name }}
        echo "action-name=${{ inputs.test_actions_name }}" >> $GITHUB_OUTPUT
      shell: bash
