name: "Hello World"
description: "Greet someone"
runs:
  using: "composite"
  steps:
    - name: Run hello world
      run: |
        echo "in composit action ${{ runner.temp }}"
        echo "in composit action ${{ github.workspace }}"
        ../_actions/${{ github.repository }}/say-hello.sh
      shell: bash
