name: "Hello World"
description: "Greet someone"
inputs:
  docker_actions_path:
    description: 'paths'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Run hello world
      run: |
        $GITHUB_ACTION_PATH/say-hello.sh
        echo "action path env variable: $GITHUB_ACTION_PATH"
      shell: bash
    - name: print everything
      run: |
        echo "github.action_path: ${{github.action_path}}"
        echo "github.event_path: ${{github.event_path}}"
        echo "github.workspace: ${{github.workspace}}"
      shell: bash
